### 7mi-TCT CONFIG ###

### コンフィグを編集したら、必ず /tctreload をしてください。

## ゲームのスタートなどができるプレイヤーを設定します。
# 例
# admin:
#   - Steve
#   - Alex
#
# オペレーターにadmin権限を与える場合はopと入力します。
admin:
  - op

roles:
## それぞれの役職の人数を変更します。
#
# 村人 - villagers
# 医者 - healers
# 探偵 - detectives
# 人狼 - wolves
# 狂人 - fanatics
# 妖狐 - foxes
#
# 村人の場合は設定した値は最小値になります
# 0にするとその役職は無効になります。
  count:
    villagers: 1
    healers: 1
    detectives: 1
    wolves: 1
    fanatics: 1
    foxes: 1
    immoral: 1
# 例
# count:
#   villagers: 1
#   healers: 1
#   detectives: 1
#   wolves: 1
#   fanatics: 1
#   foxes: 1
#   immoral: 1
#
# 人数が7人の場合、
# 村人: 1
# 医者: 1
# 探偵: 1
# 人狼: 1
# 狂人: 1
# 妖狐: 1
# 背徳者: 1
#
# 人数が8人の場合、
# 村人: 2
# 医者: 1
# 探偵: 1
# 人狼: 1
# 狂人: 1
# 妖狐: 1
# 背徳者: 1
#
# 人数が9人の場合、
# 村人: 3
# 医者: 1
# 探偵: 1
# 人狼: 1
# 狂人: 1
# 妖狐: 1
# 背徳者: 1
#
# 人数が6人以下の場合、
# 開始不可


#ゲーム開始時に所持しているコイン枚数
#
#デフォルト
# coin:
#   villagers: 0
#   healers: 0
#   detectives: 2
#   wolves: 2
#   fanatics: 0
#   foxes: 0
#   immoral: 0
  coin:
    villagers: 0
    healers: 0
    detectives: 2
    wolves: 2
    fanatics: 0
    foxes: 1
    immoral: 0

countdown:
  #デフォルト: 10秒
  prestart: 10 #準備時間 (秒)
  #デフォルト: 210秒
  game: 210 #ゲーム残り時間 (秒)
  addcount:
    #デフォルト: 20秒
    kill: 20 #キルしたときに増える時間 (秒)

#デフォルト: 20秒
quickchat-cooldown: 20 #クイックチャットのクールタイム (秒)

#デフォルト: 20秒
heal-station-cooldown: 20 #回復ステーションのクールタイム (秒)

#デフォルト: 70秒
fox-reveal-time-default: 70 #妖狐の正体がばれる時間 (秒)
#デフォルト: 60秒
fox-reveal-time: 60 #妖狐の正体がばれる時間 (秒)

#デフォルト: 180秒後
first-coin-time: 180 #コインが配られる時間 (秒後)

#ポーションエフェクトの設定
potion-effect:
  #呪い
  slowness:
    #デフォルト: 10s
    duration: 10s #鈍足が付与される時間 (tickの時は t, 秒の時は s)
    #デフォルト: 2
    level: 2 #鈍足の強さ
  #スピードポーション
  speed:
    #デフォルト: 180s
    duration: 180s
    #デフォルト: 1
    level: 1
  #回復スプラッシュポーション
  heal:
    #デフォルト: 2
    level: 2

#ゲーム中に付与されるエフェクトの設定
effect:
  #医者の剣で付与される再生エフェクト
  healer-regeneration:
    #デフォルト: 1s
    duration: 1s
    #デフォルト: 3
    level: 3
  #探偵が置いた回復ブロックをクリックしたときに付与される再生エフェクト
  detective-regeneration:
    #デフォルト: 2s
    duration: 2s
    #デフォルト: 3
    level: 3

#花火の設定
fireworks:
  #デフォルト: 1
  power: 1 #花火の威力
  #デフォルト: BURST
  type: BURST #花火の種類
  #デフォルト:
  # - 0xFF0000
  colors: #花火の色 (色コードを16進数, 10進数のどちらかで表す)
    - 0xFF0000
  #デフォルト:
  # - 0xFF0000
  fades: #花火のフェード
    - 0xFF0000

#ここは変更しないでください
version: ${version}